slice_name: Family Violence Rates
description: null
certified_by: null
certification_details: null
viz_type: big_number_total
params:
  datasource: 1__table
  viz_type: big_number_total
  metric: family_violence_rate
  adhoc_filters:
  - clause: WHERE
    subject: occ_month
    operator: TEMPORAL_RANGE
    comparator: No filter
    expressionType: SIMPLE
  header_font_size: 0.4
  subtitle_font_size: 0.15
  metric_name_font_size: 0.15
  y_axis_format: ',.1%'
  time_format: smart_date
  conditional_formatting: []
  extra_form_data: {}
  dashboards: []
query_context: '{"datasource":{"id":1,"type":"table"},"force":false,"queries":[{"filters":[{"col":"occ_month","op":"TEMPORAL_RANGE","val":"No
  filter"}],"extras":{"having":"","where":""},"applied_time_extras":{},"columns":[],"metrics":["family_violence_rate"],"annotation_layers":[],"series_limit":0,"group_others_when_limit_reached":false,"order_desc":true,"url_params":{},"custom_params":{},"custom_form_data":{}}],"form_data":{"datasource":"1__table","viz_type":"big_number_total","metric":"family_violence_rate","adhoc_filters":[{"clause":"WHERE","subject":"occ_month","operator":"TEMPORAL_RANGE","comparator":"No
  filter","expressionType":"SIMPLE"}],"header_font_size":0.4,"subtitle_font_size":0.15,"metric_name_font_size":0.15,"y_axis_format":",.1%","time_format":"smart_date","conditional_formatting":[],"extra_form_data":{},"dashboards":[],"force":false,"result_format":"json","result_type":"full"},"result_format":"json","result_type":"full"}'
cache_timeout: null
uuid: 0fc50148-17a8-480f-9913-6416981592ee
version: 1.0.0
dataset_uuid: ac9bd330-8206-4ba0-9b0e-33a3487d285c
