slice_name: Incident Counts
description: null
certified_by: null
certification_details: null
viz_type: big_number_total
params:
  datasource: 1__table
  viz_type: big_number_total
  slice_id: 1
  metric: total_incidents
  adhoc_filters:
  - clause: WHERE
    comparator: No filter
    expressionType: SIMPLE
    operator: TEMPORAL_RANGE
    subject: occ_month
  header_font_size: 0.4
  subtitle_font_size: 0.15
  y_axis_format: ',.0f'
  time_format: smart_date
  conditional_formatting: []
  extra_form_data: {}
  dashboards: []
query_context: '{"datasource":{"id":1,"type":"table"},"force":false,"queries":[{"filters":[{"col":"occ_month","op":"TEMPORAL_RANGE","val":"No
  filter"}],"extras":{"having":"","where":""},"applied_time_extras":{},"columns":[],"metrics":["total_incidents"],"annotation_layers":[],"series_limit":0,"group_others_when_limit_reached":false,"order_desc":true,"url_params":{},"custom_params":{},"custom_form_data":{}}],"form_data":{"datasource":"1__table","viz_type":"big_number_total","slice_id":1,"metric":"total_incidents","adhoc_filters":[{"clause":"WHERE","comparator":"No
  filter","expressionType":"SIMPLE","operator":"TEMPORAL_RANGE","subject":"occ_month"}],"header_font_size":0.4,"subtitle_font_size":0.15,"y_axis_format":",.0f","time_format":"smart_date","conditional_formatting":[],"extra_form_data":{},"dashboards":[],"force":false,"result_format":"json","result_type":"full"},"result_format":"json","result_type":"full"}'
cache_timeout: null
uuid: d99af6af-459e-409d-8f93-bfc99ddc36f9
version: 1.0.0
dataset_uuid: ac9bd330-8206-4ba0-9b0e-33a3487d285c
